# Monte Carlo simulation on 2D Ising model

This is a simple excisise of 2D Ising model.


In [21]:
#----------------------------------------------------------------------#
# Import operator numpy
#----------------------------------------------------------------------#
import numpy as np

#----------------------------------------------------------------------#
#   Check periodic boundary conditions 
#----------------------------------------------------------------------#
def bc(i):
    if i+1 > SIZE-1:
        return 0
    if i-1 < 0:
        return SIZE-1
    else:
        return i

#----------------------------------------------------------------------#
#   Calculate internal energy
#----------------------------------------------------------------------#
def energy(system, N, M):
    return -1 * system[N,M] * (system[bc(N-1), M]
                               + system[bc(N+1), M]
                               + system[N, bc(M-1)]
                               + system[N, bc(M+1)])


#----------------------------------------------------------------------#
#   Build the system
#----------------------------------------------------------------------#
def build_system():
    system = np.random.random_integers(0,1,(SIZE,SIZE))
    system[system==0] =- 1

    return system

system = build_system()

#----------------------------------------------------------------------#
#   Monte carlo loops
#----------------------------------------------------------------------#

SIZE = 10
STEPS = 100000
T = 0.1

def main(T):
    system = build_system()
    print system
    
    for step, x in enumerate(range(STEPS)):
        M = np.random.randint(0,SIZE)
        N = np.random.randint(0,SIZE)

        E = -2. * energy(system, N, M)

        if E <= 0.:
            system[N,M] *= -1
        elif np.exp(-1./T*E) > np.random.rand():
            system[N,M] *= -1
    print system


print '='*70
print '\tMonte Carlo Statistics for an ising model with'
print '\t\tperiodic boundary conditions'
print '='*70

main(T)


/Users/qiuruihao/.conda/envs/py2/lib/python2.7/site-packages/ipykernel/__main__.py:33: DeprecationWarning: This function is deprecated. Please call randint(0, 1 + 1) instead


	Monte Carlo Statistics for an ising model with
		periodic boundary conditions
Choose the temperature for your run (0.1-100)
[[-1  1 -1 -1  1 -1  1  1  1  1]
 [ 1 -1  1  1 -1  1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1 -1  1  1 -1  1]
 [-1 -1  1  1 -1 -1  1 -1  1  1]
 [ 1 -1 -1 -1 -1 -1 -1  1  1  1]
 [ 1  1  1  1  1 -1  1 -1  1  1]
 [ 1 -1 -1  1 -1 -1 -1  1 -1  1]
 [ 1 -1 -1  1 -1  1  1 -1  1 -1]
 [-1 -1 -1  1 -1  1 -1 -1 -1 -1]
 [ 1 -1 -1 -1  1  1 -1 -1  1 -1]]
[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]
