## Markov chain


### 1. Basic

In [58]:
import numpy as np
from numpy.random import uniform

P = [[0.65, 0.28, 0.07],
     [0.15, 0.67, 0.18], 
     [0.12, 0.36, 0.52]]
P = np.asarray(P)

idx = 0
index = []
step = 0
n = 100
while step < n:
    A = np.cumsum(P[idx,:])
    idx = np.searchsorted(A, uniform(0, 1))
    index = index + [idx]
    step += 1
print index


[0, 0, 0, 1, 1, 1, 1, 2, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 2, 0, 1, 1, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 2, 1, 2, 0, 2, 2, 2, 1, 0, 2, 2, 2, 2, 1, 1, 1, 0, 0, 1, 1, 1, 2, 2, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 2]


In [60]:
Px = np.matrix(P)**40

print Ax

[[ 0.28650138  0.48852158  0.22497704]
 [ 0.28650138  0.48852158  0.22497704]
 [ 0.28650138  0.48852158  0.22497704]]
